### ISSUE TITLE
uploadskeletons exptected input

### ISSUE THREAD

**Issue by dokato** [SridharJagannathan/pyroglancer#12]
hey @SridharJagannathan, I was wondering what is expected input to `uploadskeletons` function. I have a bunch of skeletons in swc format, that I read to navis:

```python
swcs = navis.read_swc('data/')
```

But then:
```python
uploadskeletons(swcs, skel_ids, skel_names, hostdirectory, 'longest_neurites')
```

Gives the following error:
```
AttributeError                            Traceback (most recent call last)
Input In [31], in <module>
----> 1 uploadskeletons(swcs, skel_ids, skel_names, hostdirectory, 'longest_neurites')

File ~/miniforge3/envs/newpyg2/lib/python3.9/site-packages/pyroglancer/skeletons.py:143, in uploadskeletons(skelsource, skelseglist, skelnamelist, path, layer_name)
    121 def uploadskeletons(skelsource, skelseglist, skelnamelist, path, layer_name):
    122     """Upload skeleton (of cloudvolume class) to a local server.
    123 
    124     Parameters
   (...)
    140         object of cloudvolume class
    141     """
    142     info = {"@type": "neuroglancer_skeletons",
--> 143             "transform": skelsource[0].transform.flatten(),
    144             "vertex_attributes": [{"id": "radius", "data_type": "float32", "num_components": 1}],
    145             "scales": "um"}
    146     path = 'file://' + path + '/precomputed/' + layer_name
    147     cv = CloudVolume(path, info=info)

File ~/miniforge3/envs/newpyg2/lib/python3.9/site-packages/navis/core/skeleton.py:199, in TreeNeuron.__getattr__(self, key)
    193 """We will use this magic method to calculate some attributes on-demand."""
    194 # Note that we're mixing @property and __getattr__ which causes problems:
    195 # if a @property raises an Exception, Python falls back to __getattr__
    196 # and traceback is lost!
    197 
    198 # Last ditch effort - maybe the base class knows the key?
--> 199 return super().__getattr__(key)

File ~/miniforge3/envs/newpyg2/lib/python3.9/site-packages/navis/core/base.py:156, in BaseNeuron.__getattr__(self, key)
    153             return 'NA'
    154     return None
--> 156 raise AttributeError(f'Attribute "{key}" not found')

AttributeError: Attribute "transform" not found
```

I tried to convert it to a regular list of TreeNeurons:

```python
skel_list = [swcs[i] for i in range(len(swcs))]
```

But the error is the same. Any step that I'm missing?

**Comment by SridharJagannathan** [comment]
Hi @dokato ,
For converting swc/treeneuron(s) to neuroglancer format, I have made an example here (look at the `skeleton part..` section)
https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/examples/generate_datasets/generate_hemibrain2flywire.ipynb

The basic strategy is that:
1) read the swc via navis (which you have already done like `navis.read_swc`)
2) next use the api `to_ngskeletons` whose input are treeneurons and returns a `skelsource`
3) next use the api `to_precomputedskels` whose input are skelsource and returns a `skelsource`
4) next use the api `to_precomputedskelsinfo` to set the info file to the host directory.

You can see in the example notebook, how i have fetched from `hemibrain` and then converted them to skeletons to display in `flywire`

let me know if it works?

**Comment by dokato** [comment]
Thanks @SridharJagannathan for a prompt reply. I moved on with your advise, but when I try to visualise the skeletons locally, I get:

![Screenshot 2022-01-24 at 11 13 05](https://user-images.githubusercontent.com/4547289/150772798-5468c41f-5c46-4c6b-bf89-dd11759e00ad.png)

I checked the paths, they look correct. However, comparing with meshes the precomputed file ids look weird:
```
fff14b96-d64e-449c-bd28-07787b7007db
fe44783e-e8b5-4db2-83c4-d0dc1031f00d
```

is this how it should be?

**Comment by dokato** [comment]
This must be some problem with default "skelsource" ids. When I modified them to:
```
start_idx = 1000
skelseglist_modified = []
for i in range(len(skelsource)):
    skelsource[i].id = str(start_idx + i)
    skelseglist_modified.append(str(start_idx + i))
```
All worked fine.

**Comment by SridharJagannathan** [comment]
Yes, they are the problem sometimes when you convert using `navis` it returns such hexadecimal characters for the neuron ids (sometimes i think also for meshes), but the `neuroglancer` framework only accepts `unit64`, so convert those ids to the relevant body ids or some other number etc

**Comment by SridharJagannathan** [comment]
or when you read the swc using `navis` you can give the `id` as input and read it out, so you can avoid this issue, see here for an example:
https://github.com/SridharJagannathan/pyroglancer/blob/0af3351e5f504f5d4feb9013cf5814c6032b6001/pyroglancer/tests/test_skeletons.py#L58-L59

**Comment by dokato** [comment]
I see, cool, cool. The most important that it works. Maybe worth adding a note to the docstrings. Or warning if possible to detect? Closing for now. Thanks for help again!
