### ISSUE TITLE
Adding FlyWire body IDs to URL

### ISSUE THREAD

**Issue by eichlerkathi** [SridharJagannathan/pyroglancer#2]
Function for adding body IDs to display while creating a FlyWire URL.
Similar to fafbseg function flywire.encode_url, example:

url = fafbseg.flywire.encode_url(segments=720575940642841623)

**Comment by SridharJagannathan** [comment]
@eichlerkathi Can you please check if it works, the example is under:
https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/examples/unit_examples.ipynb
you can start looking from example 3 onwards

**Comment by eichlerkathi** [comment]
Works, thank you!
