### ISSUE TITLE
Change of mesh identity when multiple meshes are plotted in one flywire link

### ISSUE THREAD

**Issue by YijieYin** [SridharJagannathan/pyroglancer#5]
I plot ALad1 (VFB_00020032 ) first in one flywire link, 
![Screenshot 2021-04-13 at 13 12 05](https://user-images.githubusercontent.com/37304606/114556097-439ba780-9c60-11eb-9143-da68714fc732.png)
ALl1 (VFB_00020008 ) in another flywire link. 
![Screenshot 2021-04-13 at 13 29 03](https://user-images.githubusercontent.com/37304606/114556127-4e563c80-9c60-11eb-8f2e-6925e5cde9c7.png)
Then If I move the LM layer from one flywire link to another through clicking the 3 vertical dots on the top right of Flywire -> edit JSON state -> expanding 'layers', and copy and paste the volumes layer from one to the other, such that the latter flywire link has 2 layers of LM data of different lineages, these 2 layers actually give the same LM data of the same lineage (I think the one originally in the link). Please note layer 4 and 5 are both volumes in the screenshot below. The first is the original ALad1, and the second ALl1 that I pasted from another flywire link. 
![Screenshot 2021-04-13 at 13 29 38](https://user-images.githubusercontent.com/37304606/114556183-5d3cef00-9c60-11eb-92cd-958c2292a1e4.png)

Here I've used the [gal4line2flyiwre](https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/examples/gal4line2flywire.ipynb) example for both. [Here](https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/4757698205712384)'s a flywire link containing the brain mesh that you could use for `shorturl`. Please let me know if you'd like all the code I used pasted here.

**Comment by SridharJagannathan** [comment]
Hi @YijieYin : Thanks for reporting this, I suspect the files are being overwritten as the same layer name is being given. So I suggest for the following:
```
tmpviewer = add_flywirelayer(flywireurl2dict(shorturl), layer_kws = {'type': 'volume_01','name': 'ALad1',
                                                        'source': vfb2flywiremesh_01,'color': 'red'})

tmpviewer = add_flywirelayer(flywireurl2dict(shorturl), layer_kws = {'type': 'volume_02','name': 'ALl1',
                                                        'source': vfb2flywiremesh_02'color': 'blue'})

```
You can also pass them in a single line with a list as well.
Let me know if this works.

**Comment by YijieYin** [comment]
Here's the code. I simply ran it once for the first mesh to get a flywire link, and again for the second (after changing the `vfb_id`) for another flywire link. Then I copy-pasted the JSON from one to the other, as I said above. 
```python
import navis
import fafbseg
import flybrains

import os
import numpy as np
import pandas as pd
import copy

from pyroglancer.localserver import startdataserver, closedataserver
from pyroglancer.flywire import flywireurl2dict, add_flywirelayer
from pyroglancer.utils import pointcloud2meshes

import trimesh as tm
import open3d as o3d 


from vfb_connect.cross_server_tools import VfbConnect
vc = VfbConnect()
vfb_id = 'VFB_00020032' 
# 'VFB_00020048': DM6
# 'VFB_00020085': DM4
# VFB_00020010: SMPpv1
# VFB_00020051: SLPal3
# VFB_00020052: SLPal4
# VFB_00020059: SLPal5
# VFB_00020031: PSp3
# VFB_00020071: VLPp2
# VFB_00020203: DM5 (cleaner) 
# VFB_00020020: DM5 (messy)
# VFB_00020023: SLPpl2
# VFB_00020008 ALl1
vcinfo = vc.neo_query_wrapper.get_anatomical_individual_TermInfo([vfb_id])
image_folder = vcinfo[0]['channel_image'][0]['image']['image_folder'] + 'volume.obj'
image_folder

vfb_mesh = tm.load_remote(image_folder)
vfb_mesh 
mesh_files = '/Users/yijieyin/Documents/Python/Pyroglancer/gal4_lines/' + vfb_id + '.ply'
mesh_files
tempval = vfb_mesh.export(mesh_files)

pcd = o3d.io.read_point_cloud(mesh_files)
pcd.estimate_normals()

# estimate radius for rolling ball
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist

# This will take some time. This is generating a point cloud from the nrrd file 
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd,
           o3d.utility.DoubleVector([radius, radius * 2]))

# create the triangular mesh with the vertices and faces from open3d
tri_mesh = tm.Trimesh(np.asarray(mesh.vertices), np.asarray(mesh.triangles),
                          vertex_normals=np.asarray(mesh.vertex_normals))

# Checks if the mesh is broken 
tm.convex.is_convex(tri_mesh)

vfb_mesh = navis.Volume(tri_mesh) 


jrc2018u_mesh = navis.Volume(flybrains.JRC2018U.mesh)
vfb_mesh.color = 'blue'
vfb_mesh
fig, ax = navis.plot2d([vfb_mesh,jrc2018u_mesh], method='2d')
fig.gca().invert_yaxis()
vfbmesh_xyz_02 = pd.DataFrame(list(map(np.ravel, vfb_mesh.vertices)), columns=['x', 'y', 'z'])
vfb2flywiremesh = copy.deepcopy(vfb_mesh)
# Transform from Janelia Research Campus 2018 Unisex into Flywire space
vfb2flywiremesh_xyz = navis.xform_brain(vfbmesh_xyz_02[['x','y','z']],source='JRC2018U', target='FLYWIRE')
vfb2flywiremesh.vertices = vfb2flywiremesh_xyz
vfb2flywiremesh 


# You should always close this even if you shut down the terminal 
startdataserver()
# An empty url containing the brain mesh 
shorturl = 'https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/4757698205712384' 


# just a random number to show in FlyWire
vfb2flywiremesh.id = 1
# Note the type here is volumes 
# The link this cell gives is the one that has the pre-computed mesh. 
shorturl = add_flywirelayer(flywireurl2dict(shorturl), layer_kws = {'type': 'volumes','name': 'ALad1',
                                                        'source': vfb2flywiremesh,'color': 'white'})


# Make sure you run this at the end: 
closedataserver()
```

**Comment by SridharJagannathan** [comment]
@YijieYin: Please find the updated notebook with much more simpler interface here:
https://github.com/SridharJagannathan/pyroglancer/blob/a227084bcf44556e0d86a3cb61353d953d5badf8/docs/source/tutorials/gal4line2flywire.ipynb
It highly recommended to use this version, also you can see there how I have named layers as tabs etc in cell 30,31.
Also another option is available in cell 32, where you can add them all in one tab, and simply select them like how you do for segments.
